version: '3'

services:
    sql:
        build: ./L2E4/
        command: --default-authentication-plugin=mysql_native_password
    
    web:
        build: ./L2E2/
        depends_on: 
            - sql
        ports:
            - "7000:80"