apiVersion: apps/v1
kind: Deployment
metadata:
  name: momac18
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql-pod
  template:
    metadata:
      labels:
        app: sql-pod
    spec:
      containers:
      - name: h0tsaucesql
        args:  --default-authentication-plugin=mysql_native_password
        image: h0tsauce/sqlfile
        ports:
        - containerPort: 3306
--- 
apiVersion: v1
kind: Service
metadata:
  name: sql
spec:
  ports:
  - port: 80
    targetPort: 3306
  selector:
    app: sql-pod
