# L5E5.yml
apiVersion: apps/v1    
kind: Deployment       
metadata:
  name: h0tsauce
spec:
  selector:
    matchLabels:       
      component: h0tsauce
  replicas: 1
  template:
    metadata:
      labels:
        component: h0tsauce
    spec:
      containers:
        - name: spekt8
          image: ahmadhamid/spekt8
          ports:
            - containerPort: 3000